# Here we will automate the process of manually running each program
# First we want to define the dependencies of different steps in
# out computation on each other.

# We need to run the simulation, before we perform the statistics.
# We need to perform statistics, before we can prepare graphics.
# Before writing the Makefile, draw a dependency flow chart showing
# the different stpdf in the computation and their dependencies.

# Each step is called a target, and everything it depends on it called
# a dependency

# Write your target, followed by a ':' , then list its dependencies
# Note that there is dependency on both a program and some data
# which a previous program would have generated

# <target>: <dependencies>
# <tab><rule>

#TODO Your code here

# Finally, there is one target that cleans up everything.
# It is called `clean'. Here, we just delete all the
# outputs of all programs.

clean:
	rm -rf *.pkl
	rm -rf *.pdf

